### ISSUE TITLE
yum install docker-client でエラーになる

### ISSUE THREAD

**Issue by akira393** [infra-ci-book/ci-on-docker#1]
readme.mdの手順になっとり、mac上のvirtualbox上に環境を構築した。
しかし、

>ci-on-docker のプロジェクトページから CI/CD -> pipelines -> run pipeline からパインプラインを実行する。

において、パイプラインが走ったが、
yum install -y ansible docker-client 
にて、docker-clientはありませんとのエラーになる。

ご教授を願いたい。お願いします。

追記　エラー箇所の内容です
```
..
..
Complete!
$ yum install -y ansible docker-client
Extra Packages for Enterprise Linux 8 - x86_64  439 kB/s | 6.0 MB     00:14    
Last metadata expiration check: 0:00:11 ago on Sun Mar 15 09:15:04 2020.
No match for argument: docker-client
Error: Unable to find a match: docker-client
ERROR: Job failed: exit code 1
```

**Comment by akira393** [comment]
centos8をパイプラインの中でインストールしていることが原因でした．

**Comment by irixjp** [comment]
CentOS8 ですと podman とかに変えないとダメっぽい感じですね。
いったんお試しいただくには CentOS7 を使ってもらえるといいかと思います！

**Comment by akira393** [comment]
通りました！7.3を指定してciを起動したところ、通りました。ありがとうございます。
